# Resource declaration
# It uses regular expression to match the route that
# is assigned to the resources
# Controller with a (.do) is only for backward compatibility
# Stick with resources that are domain models only
- peer:
  - document:
    - comment:
      - like
    - tag
  - profile:
    - full
    - avatar:
      - upload
  - feed
- group(\.do)?:
  - broadcast
- tag
- tagcloud
- search
- reset(\.do)?
- upload(\.do)?
- vote(\.do)?
- DocumentAjax(.do)?
- logout






