# Resource declaration
# It uses regular expression to match the route that
# is assigned to the resources
# Controller with a (.do) is only for backward compatibility
# Stick with resources that are domain models only
- peer:
  - document:
    - comment:
      - like
    - tag
  - profile:
    - full
    - avatar
  - feed
- group
- tag
- tag_autocomplete_ajax
- tagsearch
- search
- search_autocomplete_ajax
- reset(\.do)?
- upload(\.do)?
- vote(\.do)?
- logout






