ALTER TABLE `avatars` ADD COLUMN x1 INT (7) DEFAULT 0;
ALTER TABLE `avatars` ADD COLUMN x2 INT (7) DEFAULT 50;
ALTER TABLE `avatars` ADD COLUMN y1 INT (7) DEFAULT 0;
ALTER TABLE `avatars` ADD COLUMN y2 INT (7) DEFAULT 50;
ALTER TABLE `avatars` DROP COLUMN img_data;
ALTER TABLE `avatars` DROP COLUMN img_title;
ALTER TABLE `avatars` ADD COLUMN filename VARCHAR(127) DEFAULT NULL;
